### ISSUE TITLE
Keyboard navigation in the treeview selects hidden items

### ISSUE THREAD

**Issue by GinoF** [Pangoraw/git-hide#3] opened 2016-02-18 16:23 UTC

**Comment by Pangoraw** [comment] 2016-02-25 17:58
Hello, 
Thanks for reporting :)
But unfortunably, I think I can not fix this issue because I can only hide the HTML elements that represents files. It is caused by [atom tree-view](https://github.com/atom/tree-view) which doesn't provide a complete enough API.

So for now I am stuck :/

**Comment by GinoF** [comment] 2016-02-25 21:21
Thanks for getting back to me, and creating this package :smile: 

I've actually just started using atom, and haven't done any atom package development, so this suggestion is coming from nowhere:

Is it possible to override the moveDown and MoveUp functions?
https://github.com/atom/tree-view/blob/master/lib/tree-view.coffee#L341

If it's possible you can check for your ignore classes.

**EDIT**: Ah... I just looked at that API section. It looks pretty limiting :confused:

**Comment by Pangoraw** [comment] 2016-03-11 09:55
Hi, 
One idea could be to actually edit the files. 
But this could be dangerous. 
I have seen multiple pull request about the creation of an API but none has been successful yet.

**Comment by Pangoraw** [comment] 2016-09-05 18:40
Atom's tree-view plugin now has an option to hide the files mentioned in the gitignore file. So it is basically the function of git-hide bundled within the default plugins (without keyboard shortcut for the moment). I will close this issue because you can find a better way to do the same thing :)

**Closed as completed by Pangoraw** 2016-09-05 18:40 UTC
Labels: help wanted
